name: Greeting from MangChing
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
          MY_VAR: Hi there! Myname is
          FIRST_NAME: MangChing
          MIDDLE_NAME: Martin
          LAST_NAME: Lee
      run:
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
         
      
  


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
